INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('USD', '$', '$', 'US Dollar');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('CAD', 'CA$', '$', 'Canadian Dollar');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('EUR', '€', '€', 'Euro');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('AED', 'AED', 'د.إ.‏', 'United Arab Emirates Dirham');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('AFN', 'Af', '؋', 'Afghan Afghani');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('ALL', 'ALL', 'Lek', 'Albanian Lek');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('AMD', 'AMD', 'դր.', 'Armenian Dram');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('ARS', 'AR$', '$', 'Argentine Peso');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('AUD', 'AU$', '$', 'Australian Dollar');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('AZN', 'man.', 'ман.', 'Azerbaijani Manat');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('BAM', 'KM', 'KM', 'Bosnia-Herzegovina Convertible Mark');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('BDT', 'Tk', '৳', 'Bangladeshi Taka');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('BGN', 'BGN', 'лв.', 'Bulgarian Lev');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('BHD', 'BD', 'د.ب.‏', 'Bahraini Dinar');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('BIF', 'FBu', 'FBu', 'Burundian Franc');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('BND', 'BN$', '$', 'Brunei Dollar');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('BOB', 'Bs', 'Bs', 'Bolivian Boliviano');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('BRL', 'R$', 'R$', 'Brazilian Real');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('BWP', 'BWP', 'P', 'Botswanan Pula');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('BYN', 'Br', 'руб.', 'Belarusian Ruble');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('BZD', 'BZ$', '$', 'Belize Dollar');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('CDF', 'CDF', 'FrCD', 'Congolese Franc');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('CHF', 'CHF', 'CHF', 'Swiss Franc');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('CLP', 'CL$', '$', 'Chilean Peso');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('CNY', 'CN¥', 'CN¥', 'Chinese Yuan');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('COP', 'CO$', '$', 'Colombian Peso');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('CRC', '₡', '₡', 'Costa Rican Colón');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('CVE', 'CV$', 'CV$', 'Cape Verdean Escudo');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('CZK', 'Kč', 'Kč', 'Czech Republic Koruna');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('DJF', 'Fdj', 'Fdj', 'Djiboutian Franc');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('DKK', 'Dkr', 'kr', 'Danish Krone');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('DOP', 'RD$', 'RD$', 'Dominican Peso');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('DZD', 'DA', 'د.ج.‏', 'Algerian Dinar');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('EEK', 'Ekr', 'kr', 'Estonian Kroon');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('EGP', 'EGP', 'ج.م.‏', 'Egyptian Pound');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('ERN', 'Nfk', 'Nfk', 'Eritrean Nakfa');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('ETB', 'Br', 'Br', 'Ethiopian Birr');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('GBP', '£', '£', 'British Pound Sterling');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('GEL', 'GEL', 'GEL', 'Georgian Lari');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('GHS', 'GH₵', 'GH₵', 'Ghanaian Cedi');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('GNF', 'FG', 'FG', 'Guinean Franc');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('GTQ', 'GTQ', 'Q', 'Guatemalan Quetzal');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('HKD', 'HK$', '$', 'Hong Kong Dollar');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('HNL', 'HNL', 'L', 'Honduran Lempira');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('HRK', 'kn', 'kn', 'Croatian Kuna');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('HUF', 'Ft', 'Ft', 'Hungarian Forint');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('IDR', 'Rp', 'Rp', 'Indonesian Rupiah');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('ILS', '₪', '₪', 'Israeli New Sheqel');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('INR', 'Rs', 'টকা', 'Indian Rupee');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('IQD', 'IQD', 'د.ع.‏', 'Iraqi Dinar');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('IRR', 'IRR', '﷼', 'Iranian Rial');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('ISK', 'Ikr', 'kr', 'Icelandic Króna');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('JMD', 'J$', '$', 'Jamaican Dollar');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('JOD', 'JD', 'د.أ.‏', 'Jordanian Dinar');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('JPY', '¥', '￥', 'Japanese Yen');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('KES', 'Ksh', 'Ksh', 'Kenyan Shilling');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('KHR', 'KHR', '៛', 'Cambodian Riel');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('KMF', 'CF', 'FC', 'Comorian Franc');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('KRW', '₩', '₩', 'South Korean Won');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('KWD', 'KD', 'د.ك.‏', 'Kuwaiti Dinar');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('KZT', 'KZT', 'тңг.', 'Kazakhstani Tenge');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('LBP', 'LB£', 'ل.ل.‏', 'Lebanese Pound');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('LKR', 'SLRs', 'SL Re', 'Sri Lankan Rupee');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('LTL', 'Lt', 'Lt', 'Lithuanian Litas');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('LVL', 'Ls', 'Ls', 'Latvian Lats');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('LYD', 'LD', 'د.ل.‏', 'Libyan Dinar');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('MAD', 'MAD', 'د.م.‏', 'Moroccan Dirham');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('MDL', 'MDL', 'MDL', 'Moldovan Leu');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('MGA', 'MGA', 'MGA', 'Malagasy Ariary');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('MKD', 'MKD', 'MKD', 'Macedonian Denar');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('MMK', 'MMK', 'K', 'Myanma Kyat');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('MOP', 'MOP$', 'MOP$', 'Macanese Pataca');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('MUR', 'MURs', 'MURs', 'Mauritian Rupee');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('MXN', 'MX$', '$', 'Mexican Peso');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('MYR', 'RM', 'RM', 'Malaysian Ringgit');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('MZN', 'MTn', 'MTn', 'Mozambican Metical');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('NAD', 'N$', 'N$', 'Namibian Dollar');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('NGN', '₦', '₦', 'Nigerian Naira');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('NIO', 'C$', 'C$', 'Nicaraguan Córdoba');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('NOK', 'Nkr', 'kr', 'Norwegian Krone');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('NPR', 'NPRs', 'नेरू', 'Nepalese Rupee');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('NZD', 'NZ$', '$', 'New Zealand Dollar');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('OMR', 'OMR', 'ر.ع.‏', 'Omani Rial');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('PAB', 'B/.', 'B/.', 'Panamanian Balboa');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('PEN', 'S/.', 'S/.', 'Peruvian Nuevo Sol');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('PHP', '₱', '₱', 'Philippine Peso');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('PKR', 'PKRs', '₨', 'Pakistani Rupee');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('PLN', 'zł', 'zł', 'Polish Zloty');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('PYG', '₲', '₲', 'Paraguayan Guarani');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('QAR', 'QR', 'ر.ق.‏', 'Qatari Rial');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('RON', 'RON', 'RON', 'Romanian Leu');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('RSD', 'din.', 'дин.', 'Serbian Dinar');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('RUB', 'RUB', '₽.', 'Russian Ruble');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('RWF', 'RWF', 'FR', 'Rwandan Franc');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('SAR', 'SR', 'ر.س.‏', 'Saudi Riyal');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('SDG', 'SDG', 'SDG', 'Sudanese Pound');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('SEK', 'Skr', 'kr', 'Swedish Krona');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('SGD', 'S$', '$', 'Singapore Dollar');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('SOS', 'Ssh', 'Ssh', 'Somali Shilling');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('SYP', 'SY£', 'ل.س.‏', 'Syrian Pound');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('THB', '฿', '฿', 'Thai Baht');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('TND', 'DT', 'د.ت.‏', 'Tunisian Dinar');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('TOP', 'T$', 'T$', 'Tongan Paʻanga');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('TRY', 'TL', 'TL', 'Turkish Lira');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('TTD', 'TT$', '$', 'Trinidad and Tobago Dollar');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('TWD', 'NT$', 'NT$', 'New Taiwan Dollar');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('TZS', 'TSh', 'TSh', 'Tanzanian Shilling');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('UAH', '₴', '₴', 'Ukrainian Hryvnia');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('UGX', 'USh', 'USh', 'Ugandan Shilling');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('UYU', '$U', '$', 'Uruguayan Peso');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('UZS', 'UZS', 'UZS', 'Uzbekistan Som');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('VEF', 'Bs.F.', 'Bs.F.', 'Venezuelan Bolívar');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('VND', '₫', '₫', 'Vietnamese Dong');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('XAF', 'FCFA', 'FCFA', 'CFA Franc BEAC');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('XOF', 'CFA', 'CFA', 'CFA Franc BCEAO');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('YER', 'YR', 'ر.ي.‏', 'Yemeni Rial');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('ZAR', 'R', 'R', 'South African Rand');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('ZMW', 'ZK', 'ZK', 'Zambian Kwacha');
INSERT INTO currency (code, symbol, symbol_native, name) VALUES ('ZWL', 'ZWL$', 'ZWL$', 'Zimbabwean Dollar');
